{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Population-male\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.139.1678.0 (24.12)+2a034ab280bddf891eb7bb9ebfe6996f9c3a3196"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-IN",
    "cultures": [
      {
        "name": "en-IN",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-IN",
    "tables": [
      {
        "name": "Population-male",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35a527b3-2419-40db-a7aa-aab35514a970",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          },
          {
            "name": "Column2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "19d963f5-1124-41c2-a3f4-cd2d0b12351d",
            "sourceColumn": "Column2",
            "summarizeBy": "none"
          },
          {
            "name": "Column3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "86e1f08b-d455-46ff-bd8e-aa2eeb7713bc",
            "sourceColumn": "Column3",
            "summarizeBy": "none"
          },
          {
            "name": "Column4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0bd0d871-712f-45d7-8d2a-9a85ef230ea1",
            "sourceColumn": "Column4",
            "summarizeBy": "none"
          },
          {
            "name": "Column5",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "12176fc0-8736-49e3-a3fb-9423b8121c33",
            "sourceColumn": "Column5",
            "summarizeBy": "none"
          },
          {
            "name": "Column6",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96b9546c-457a-4829-a9a5-1529c9700e3b",
            "sourceColumn": "Column6",
            "summarizeBy": "none"
          },
          {
            "name": "Column7",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c8ae2cd-a11f-4dd8-ae0b-3b170107b79e",
            "sourceColumn": "Column7",
            "summarizeBy": "none"
          },
          {
            "name": "Column8",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "79ec08dc-517e-47bd-ad02-ba8e01cb93ca",
            "sourceColumn": "Column8",
            "summarizeBy": "none"
          },
          {
            "name": "Column9",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d5e70f41-032b-4287-9deb-148bd4be8ee9",
            "sourceColumn": "Column9",
            "summarizeBy": "none"
          },
          {
            "name": "Column10",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5bff9f67-f4cb-4201-ae58-fa8b34703c35",
            "sourceColumn": "Column10",
            "summarizeBy": "none"
          },
          {
            "name": "Column11",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6d47e42-2c0d-42a4-9180-cf4154d26d00",
            "sourceColumn": "Column11",
            "summarizeBy": "none"
          },
          {
            "name": "Column12",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a7c0ee50-37f7-4008-ba27-1f5549a0360a",
            "sourceColumn": "Column12",
            "summarizeBy": "none"
          },
          {
            "name": "Column13",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "01499bad-2deb-4243-8da9-27e9c9c3dbb8",
            "sourceColumn": "Column13",
            "summarizeBy": "none"
          },
          {
            "name": "Column14",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d6194e7-c2c1-4b45-acd2-41a78dd11495",
            "sourceColumn": "Column14",
            "summarizeBy": "none"
          },
          {
            "name": "Column15",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad359896-60b4-4504-bdb5-976cf4479764",
            "sourceColumn": "Column15",
            "summarizeBy": "none"
          },
          {
            "name": "Column16",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1aaf5f53-886e-4f09-be4f-ae2cff764ff7",
            "sourceColumn": "Column16",
            "summarizeBy": "none"
          },
          {
            "name": "Column17",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d7e23292-72dd-475b-9288-f4a7a421e5d6",
            "sourceColumn": "Column17",
            "summarizeBy": "none"
          },
          {
            "name": "Column18",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "03ad1b45-ca6a-43e7-9189-5c84b4c199b1",
            "sourceColumn": "Column18",
            "summarizeBy": "none"
          },
          {
            "name": "Column19",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b50fcd28-c603-40b3-bf48-c238377856eb",
            "sourceColumn": "Column19",
            "summarizeBy": "none"
          },
          {
            "name": "Column20",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eeb115f7-cded-4359-94ea-857439004c7c",
            "sourceColumn": "Column20",
            "summarizeBy": "none"
          },
          {
            "name": "Column21",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d3af30ef-d0c4-4226-bbaa-7bf0b3dfdbb4",
            "sourceColumn": "Column21",
            "summarizeBy": "none"
          },
          {
            "name": "Column22",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e4288a59-a69e-4c39-a526-c6725551af78",
            "sourceColumn": "Column22",
            "summarizeBy": "none"
          },
          {
            "name": "Column23",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ecda3ab8-9c5e-4b6c-8e33-ad3e3aa4737f",
            "sourceColumn": "Column23",
            "summarizeBy": "none"
          },
          {
            "name": "Column24",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1b7d8675-07c5-4436-a186-2a68221765bc",
            "sourceColumn": "Column24",
            "summarizeBy": "none"
          },
          {
            "name": "Column25",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab37ef55-6f03-4581-a4ba-6cab32e78768",
            "sourceColumn": "Column25",
            "summarizeBy": "none"
          },
          {
            "name": "Column26",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c973ef5-841b-4399-8c99-2f7eb181fd88",
            "sourceColumn": "Column26",
            "summarizeBy": "none"
          },
          {
            "name": "Column27",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ca9e22d-a0a9-4e22-ae77-3eda8e52e24c",
            "sourceColumn": "Column27",
            "summarizeBy": "none"
          },
          {
            "name": "Column28",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9b8eee4-f796-4489-9876-57ca2d111111",
            "sourceColumn": "Column28",
            "summarizeBy": "none"
          },
          {
            "name": "Column29",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "88911486-4411-45e0-8774-138bcb829325",
            "sourceColumn": "Column29",
            "summarizeBy": "sum"
          },
          {
            "name": "Column30",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "223fe17d-972a-49d5-ba8e-d25dffba332b",
            "sourceColumn": "Column30",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3ab06912-befb-442a-9cf4-94c21a047d50",
        "partitions": [
          {
            "name": "Population-male",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\Admin\\Documents\\Git_Clone floder_VStudio\\PBI-Bro-Training\\Population-male.csv\"),[Delimiter=\",\", Columns=30, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}, {\"Column7\", type text}, {\"Column8\", type text}, {\"Column9\", type text}, {\"Column10\", type text}, {\"Column11\", type text}, {\"Column12\", type text}, {\"Column13\", type text}, {\"Column14\", type text}, {\"Column15\", type text}, {\"Column16\", type text}, {\"Column17\", type text}, {\"Column18\", type text}, {\"Column19\", type text}, {\"Column20\", type text}, {\"Column21\", type text}, {\"Column22\", type text}, {\"Column23\", type text}, {\"Column24\", type text}, {\"Column25\", type text}, {\"Column26\", type text}, {\"Column27\", type text}, {\"Column28\", type text}, {\"Column29\", Int64.Type}, {\"Column30\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}